var dataUrl = 'data/poikampus2.csv';
var maxZoom = 18;
var startZoom = 17;
var startLat = -6.890514273;
var startLng = 107.6109177;
var fieldSeparator = '|';
var baseUrl = 'http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.jpg';
var baseAttribution = 'Data, imagery and map information provided by <a href="http://open.mapquest.co.uk" target="_blank">MapQuest</a>, <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">CC-BY-SA</a>';
var subdomains = '1234';
var clusterOptions = {showCoverageOnHover: true, maxClusterRadius: 50};
var labelColumn = "Gedung";
var opacity = 0.6;